using System.Diagnostics;
using Mapidemic.Pages.Landing;

namespace Mapidemic.Pages.SymptomChecker;

/// <summary>
/// A class that provides a user interface for selection the method of symptom analysis
/// </summary>
public partial class ProcessPickerPage : ContentPage
{
    private const string disclaimer1 = "This symptom checker is for informational purposes only and is not a medical diagnosis. ";
    private const string disclaimer2 = "The Mapidemic team are not medical professionals, and the results generated by the ";
    private const string disclaimer3 = "symptom checker should not be used as a substitute for professional medical advice, ";
    private const string disclaimer4 = "diagnosis, or treatment. If you are experiencing concerning symptoms or believe you ";
    private const string disclaimer5 = "may be ill, please consult a licensed healthcare professional.";
    private readonly SymptomsPage sibling; // holding sibling to pop off

    /// <summary>
    /// The designated constructor for a ProcessPickerPage
    /// </summary>
    public ProcessPickerPage(SymptomsPage sibling)
    {
        InitializeComponent();
        this.sibling = sibling;
    }

    /// <summary>
    /// A function that opens the disclaimer popup
    /// when the page loads
    /// </summary>
    protected override async void OnAppearing()
    {
        bool accepted = await DisplayAlert("Disclaimer", $"{disclaimer1}{disclaimer2}{disclaimer3}{disclaimer4}{disclaimer5}", "Accept", "Decline");
        if (accepted) // continuing with symptom checking if accepted
        {
            Options.IsVisible = true;
        }
        else // closing symptom checker if declined
        {
            Popup.IsOpen = true;
            MauiProgram.businessLogic.ClearSymptoms();
            await (Parent as NavigationPage)!.PopToRootAsync();
            Popup.IsOpen = false;
        }
    }

    /// <summary>
    /// A function that directs the user to the artificial intelligence results page
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="args"></param>
    public async void OnAiImageTapped(object sender, EventArgs args)
    {
        Popup.IsOpen = true;
        try // attempting to connect to Gemini
        {
            NavigationPage parent = (Parent as NavigationPage)!;
            await MauiProgram.businessLogic.RunAiSymptomAnalysis();
            parent.Navigation.RemovePage(sibling);
            await parent.PushAsync(new AiResultsPage());
            parent.Navigation.RemovePage(this);
        }
        catch(Exception error) // could not connect to Gemini
        {
            await HomePage.ShowPopup("Unable to connect to Gemini. Please try again");
            Debug.WriteLine(error.Message);
        }
        finally // closing activity indicator
        {
            Popup.IsOpen = false;
        }
    }

    /// <summary>
    /// A function that directs the user to the statistics
    /// results page and pops off the previous screens from the navigation stack
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="args"></param>
    public async void OnStatsImageTapped(object sender, EventArgs args)
    {
        Popup.IsOpen = true;
        try // attempting statistical analysis
        {
            NavigationPage parent = (Parent as NavigationPage)!;
            await MauiProgram.businessLogic.RunStatsSymptomAnalysis();
            parent.Navigation.RemovePage(sibling);
            await parent.PushAsync(new StatsResultsPage());
            parent.Navigation.RemovePage(this);
        }
        catch(Exception error) // could not get illness information from database
        {
            await HomePage.ShowPopup("Unable to complete analysis. Please try again");
            Debug.WriteLine(error.Message);
        }
        finally // closing activity indicator
        {
            Popup.IsOpen = false;
        }
    }
}